return {
    id = "household_checklist",
    template = "household_checklist",
    output_name = "household_checklist",
    header = "Household Essentials Checklist",
    completed_date = "2026-07-18",
    columns = {
        { -- Column 1
            {
                title = "Dishwashing", items = { "Hand soap", "Dish soap", "Dish sponges", "Dish gloves", "Dishwasher pods or tablets", "Dish drying rack", "Dish brush", "Dish towels" }
            },
            {
                title = "Cleaning", items = { "All-purpose cleaner", "Disinfectant cleaner", "Glass cleaner", "Scrub brush", "White vinegar", "Microfiber cleaning cloths", "Paper towels" }
            },
            {
                title = "Organization", items = { "Closet hangers", "Storage baskets", "Drawer organizers", "Command hooks", "Shoe rack", "Laundry hamper", "Reusable shopping bags" }
            },
            {
                title = "Laundry", items = { "Laundry detergent", "Fabric softener", "Bleach", "Stain remover", "Dryer sheets" }
            },
            {
                title = "Floors", items = { "General floor cleaner", "Wood floor cleaner", "Broom and dustpan", "Floor mop", "Vacuum" }
            },
        },
        { -- Column 2
            {
                title = "Windows", items = { "Cleaning cloths", "Polishing cloths", "Glass cleaner" }
            },
            {
                title = "Trash", items = { "Large trash bags", "Small trash bags", "Compost bags" }
            },
            {
                title = "Bathroom", items = { "Cleaning gloves", "Toilet brush", "Toilet paper", "Disinfecting spray cleaner", "Shower cleaner", "Toilet bowl cleaner", "Plunger", "Drain cleaner", "Bathroom trash bags" }
            },
            {
                title = "Hygiene", items = { "Liquid hand soap", "Hand towels", "Hand sanitizer", "Tissues", "Disinfectant wipes" }
            },
            {
                title = "Kitchen", items = { "Plastic wrap (saran wrap)", "Aluminum foil", "Food storage containers", "Kitchen trash can", "Freezer bags" }
            },
            {
                title = "Supplies", items = { "Flashlight", "AA batteries", "AAA batteries", "Light bulbs", "Screwdriver set" }
            }
        }
    }
}
