return {
    id = "emergency_foodlist_teal",
    output_name = "emergency_foodlist",
    template = "emergency_foodlist",
    header = "Emergency Foodlist",
    overrides = "teal_style",
    completed_date = "2026-07-06",
    columns = {
        { -- Column 1
            {
                title = "Grains And Cereals", items = { "Instant oatmeal", "Brown rice", "Quinoa", "Instant couscous", "Pasta", "Dry cereal (granola, cornflakes)", "Crackers (whole grain, rye)", "Rice cakes", "Granola bars", "Protein bars", "Whole grain tortilla chips" }
            },
            {
                title = "Ready-To-Eat And Instant Foods", items = { "MREs (Meals Ready-to-Eat)", "Canned pasta meals", "Instant noodles", "Instant rice", "Shelf-stable protein shakes" }
            },
            {
                title = "Dry And Dehydrated Foods", items = { "Instant mashed potatoes", "Dried soup mixes", "Freeze-dried meals (camping food)", "Black beans", "Lentils", "Chickpeas", "Split peas", "Dried quinoa", "Dried bulgur", "Chia seeds", "Flaxseeds" }
            },
        },
        { -- Column 2
            {
                title = "Canned And Jarred Goods", items = { "Green beans", "Corn", "Peas", "Carrots", "Spinach", "Peaches", "Pineapple", "Pears", "Applesauce", "Tuna", "Salmon", "Chicken", "Sardines", "Beans (black, kidney, chickpeas, lentils)", "Soups (chicken noodle, vegetable, tomato)", "Stews (beef stew, chili)", "Pasta meals (spaghetti, ravioli)", "Nut butters (peanut butter, almond butter)", "Pasta sauce", "Salsa", "Jams and preserves" }
            },
            {
                title = "Dairy And Alternatives", items = { "Powdered milk", "Evaporated milk", "Sweetened condensed milk", "Shelf-Stable coffee creamer", "Shelf-stable almond milk", "Shelf-stable soy milk", "Shelf-stable coconut milk", "Ghee (clarified butter)" }
            },
        },
        { -- Column 3
            {
                title = "Condiments And Cooking Essentials", items = { "Salt", "Pepper", "Sugar", "Honey", "Vinegar", "Ketchup", "Mustard", "Hot sauce", "Soy Sauce", "Olive oil", "Vegetable oil", "Bouillon Cubes", "Baking soda", "Flour" }
            },
            {
                title = "Snacks And Sweets", items = { "Trail mix", "Nuts (almonds, walnuts, peanuts)", "Dried fruits (raisins, apricots, cranberries)", "Popcorn (pre-popped, shelf-stable)", "Chocolate bars", "Hard candies", "Fruit snacks", "Energy bars", "Beef Jerky" }
            },
            {
                title = "Beverages", items = { "Bottled water", "Electrolyte drinks (powder or liquid)", "Shelf-stable juice boxes", "Instant coffee", "Shelf-stable milk shakes", "Tea bags", "Hot chocolate mix" }
            }
        }
    }
}
