return {
    id = "grocery_list",
    output_name = "grocery_list",
    template = "grocery_list",
    header = "Grocery Checklist",
    completed_date = "2026-07-09",
    columns = {
        { -- Column 1
            {
                title = "Fruits", items =  { "apples", "apricots", "avocados", "bananas", "berries", "cherries", "grapefruit", "grapes", "kiwi", "lemons", "limes", "melons", "nectarines", "oranges", "papaya", "peaches", "pears", "plums", "pomegranate", "watermelon" }
            },
            {
                title = "Vegetables", items =  { "artichokes", "arugula", "asparagus", "beets", "broccoli", "cabbage", "cauliflower", "carrots", "celery", "chilies", "chives", "cilantro", "corn", "cucumbers", "eggplant", "garlic cloves", "green onions", "kale", "lettuce", "onions", "peppers", "potatoes", "salad greens", "spinach", "sprouts", "squash", "tomatoes", "zucchini" }
            },
            {
                title = "Breakfast", items =  { "breakfast shake", "cereal", "english muffins", "grits", "hash browns", "instant coffee", "maple syrup", "oatmeal", "pancake mix", "protein powder", "sausage patties" }
            }
        },
        { -- Column 2
            {
                title = "Meat", items =  { "bacon", "chicken", "deli meat", "ground beef", "ground turkey", "ham", "hot dogs", "pork", "sausage", "steak", "turkey" }
            },
            {
                title = "Seafood", items =  { "catfish", "cod", "crab", "halibut", "lobster", "oysters", "salmon", "shrimp", "tilapia", "tuna" }
            },
            {
                title = "Frozen", items =  { "chicken bites", "desserts", "fish sticks", "fruit", "ice", "ice cream", "ice pops", "juice", "meat", "pie shells", "pizza", "pot pies", "potatoes", "TV dinners", "vegetables", "veggie burger", "waffles" }
            },
            {
                title = "Baby", items =  { "baby cereal", "baby food", "baby shampoo", "diapers", "diaper cream", "formula", "wipes" }
            },
            {
                title = "Pets", items =  { "cat food", "cat litter", "dog food", "pet shampoo", "treats", "flea treatment" }
            }
        },
        { -- Column 3
            {
                title = "Baking", items =  { "baking powder", "baking soda", "bread crumbs", "cake decor", "cake mix", "canned milk", "chocolate chips", "cocoa", "cornmeal", "cornstarch", "flour", "food coloring", "frosting", "muffin mix", "pie crust", "shortening", "sugar (brown)", "sugar (powdered)", "sugar", "yeast" }
            },
            {
                title = "Snacks", items =  { "candy", "cookies", "crackers", "dried fruit", "fruit snacks", "gelatin", "graham crackers", "granola bars", "gum", "nuts", "popcorn", "potato chips", "pretzels", "pudding", "raisins", "rice cakes", "seeds", "tortilla chips" }
            },
            {
                title = "Bakery", items =  { "bagels", "bread", "croissants", "cookies", "croutons", "donuts", "dinner rolls", "hamburger buns", "hot dog buns", "muffins", "pastries", "pie", "pita bread", "tortillas (corn)", "tortillas (flour)" }
            }
        },
        { -- Column 4
            {
                title = "Pasta/Rice", items =  { "brown rice", "burger helper", "couscous", "elbow macaroni", "lasagna", "mac & cheese", "noodle mix", "rice mix", "spaghetti", "white rice" }
            },
            {
                title = "Cans & Jars", items =  { "applesauce", "baked beans", "black beans", "broth", "boullion cubes", "canned fruit", "canned vegetables", "carrots", "chili", "corn", "creamed corn", "jam / jelly", "mushrooms", "olives (green)", "olives (black)", "canned pasta", "pasta sauce", "peanut butter", "pickles", "pie filling", "soup" }
            },
            {
                title = "Refrigerated", items =  { "biscuits", "butter", "cheddar cheese", "cream / creamer ", "cream cheese", "dip", "eggs", "egg substitute", "feta cheese", "half & half", "jack cheese", "milk", "mozzarella", "processed cheese", "salsa", "sour cream", "swiss cheese", "whipped cream", "yogurt" }
            }
        },
        { -- Column 5
            {
                title = "Seasoning", items =  { "basil", "bay leaves", "BBQ seasoning", "cinnamon", "cloves", "cumin", "curry", "dill", "garlic powder", "garlic salt", "gravy mix", "Italian seasoning", "marinade", "meat tenderizer", "oregano", "paprika", "pepper", "poppy seed", "red pepper", "sage", "salt", "seasoned salt", "soup mix", "vanilla extract" }
            },
            {
                title = "Sauces & Condiments", items =  { "BBQ sauce", "cocktail sauce", "cooking spray", "honey", "horseradish", "hot sauce", "ketchup", "lemon juice", "mayonnaise", "mustard", "olive oil", "relish", "salad dressing", "salsa", "soy sauce", "steak sauce", "sweet & sour", "teriyaki", "vegetable oil", "vinegar" }
            },
            {
                title = "Drinks", items =  { "beer", "champagne", "club soda", "coffee", "diet soft drinks", "energy drinks", "juice", "liquor", "soft drinks", "tea", "wine" }
            }
        },
        { -- Column 6
            {
                title = "Paper Products", items =  { "aluminum foil", "coffee filters", "cups", "garbage bags", "napkins", "paper plates", "paper towels", "plastic bags", "plastic cutlery", "plastic wrap", "straws", "waxed paper" }
            },
            {
                title = "Cleaning", items =  { "air freshener", "bleach", "dish soap", "dishwasher pods", "floor cleaner", "glass spray", "laundry detergent", "fabric softener", "polish", "sponges", "vacuum bags" }
            },
            {
                title = "Personal Care", items =  { "bath soap", "bug repellant", "family planning", "feminine products", "conditioner", "cotton swabs", "dental floss", "deodorant", "facial tissue", "hair spray", "hand soap", "lip care", "lotion", "makeup", "mouthwash", "razors/blades", "shampoo", "shaving cream", "sunscreen", "toilet tissue", "toothbrush", "toothpaste" }
            },
            {
                title = "Misc. Items", items =  { "batteries", "charcoal", "greeting cards", "light bulbs" }
            }
        }
    } 
}
